version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: camping_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camping_db
      MYSQL_USER: camper
      MYSQL_PASSWORD: camper68
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: camping_wp
    restart: always
    ports:
      - "8068:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: camper
      WORDPRESS_DB_PASSWORD: camper68
      WORDPRESS_DB_NAME: camping_db
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data: